// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2-3NvLPbnLYLcLYQ-Bfx9eEEFin_fFzw',
    appId: '1:416223294952:web:afa9dc09695e1a9d27205d',
    messagingSenderId: '416223294952',
    projectId: 'gardenia-d7b46',
    authDomain: 'gardenia-d7b46.firebaseapp.com',
    storageBucket: 'gardenia-d7b46.firebasestorage.app',
    measurementId: 'G-KTZ4NHYGFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7D1hpbCvq1_Fo-1jaZY6vmnAqL2fnoNw',
    appId: '1:416223294952:android:d6b77dfda26ea87827205d',
    messagingSenderId: '416223294952',
    projectId: 'gardenia-d7b46',
    storageBucket: 'gardenia-d7b46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrvLDc-z2YxdM2c3wrgU-IRWvd9s6o-uA',
    appId: '1:416223294952:ios:166b4b8e020810d727205d',
    messagingSenderId: '416223294952',
    projectId: 'gardenia-d7b46',
    storageBucket: 'gardenia-d7b46.firebasestorage.app',
    iosBundleId: 'com.example.gardenia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrvLDc-z2YxdM2c3wrgU-IRWvd9s6o-uA',
    appId: '1:416223294952:ios:166b4b8e020810d727205d',
    messagingSenderId: '416223294952',
    projectId: 'gardenia-d7b46',
    storageBucket: 'gardenia-d7b46.firebasestorage.app',
    iosBundleId: 'com.example.gardenia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2-3NvLPbnLYLcLYQ-Bfx9eEEFin_fFzw',
    appId: '1:416223294952:web:7b32b3384d3e6d6b27205d',
    messagingSenderId: '416223294952',
    projectId: 'gardenia-d7b46',
    authDomain: 'gardenia-d7b46.firebaseapp.com',
    storageBucket: 'gardenia-d7b46.firebasestorage.app',
    measurementId: 'G-BWMBW5948Z',
  );
}
